### ISSUE TITLE
MM TBM 930  new update on Github is not visible by Downloader

### ISSUE THREAD

**Issue by krzysk1** [NicolasConstant/msfs-community-downloader#35] opened 2021-09-16 11:37 UTC
**Describe the bug**
There is newer version of  MM TBM 930 on Github ie v0.6.1,  but Downloader still provide older v0.6.0 beta #1
What is wrong?

**Comment by netsonics** [comment] 2021-09-16 15:23
I am curious also...

**Comment by NicolasConstant** [comment] 2021-09-16 15:52
duplicate of #34 
(update the profile in "Add Packages" 😉)

**Closed by NicolasConstant** 2021-09-16 15:52 UTC

**Comment by krzysk1** [comment] 2021-09-17 06:49
thanks
